{{- $secrets := pick $.Values.config "SECRET_KEY" "MAIL_PASSWORD" }}
{{ if gt (len (keys $secrets)) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otterwiki.fullname" . }}-config
  labels:
    {{- include "otterwiki.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $val := $secrets }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end }}
