# Default values for otterwiki.
image:
  repository: redimp/otterwiki
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

## Configure the otterwiki using this mapping. The configuration will be stored
## in a configMap or for those variables considered as secret in a Secret.
## Check https://otterwiki.com/Configuration for a complete list of
## config variables.
config: {}
  # SITE_NAME: Otterwiki
  # RETAIN_PAGE_NAME_CASE: false
  # GIT_WEB_SERVER: false

## env sets environment variables to pass to the container. Can be set as name/value pairs,
## read from secrets or configmaps. For the otterwiki configuration stick to the config dict
## these will we stored in a configMap and the secrets in a Secret.
env: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: otterwiki.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: otterwiki-local-tls
  #    hosts:
  #      - otterwiki.local

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

persistence:
  enabled: true
  size: 512Mi
  accessMode: ReadWriteOnce
  annotations: {}

nodeSelector: {}

tolerations: []

affinity: {}
