version: '3'
services:
  otterwiki:
    image: redimp/otterwiki:2
    # for testing local versions via 'docker-compose up --build'
    build: ../..
    restart: unless-stopped
    ports:
      # forward the http port to 8080
      - "8080:80"
    volumes:
      # mount the local directory with the example plugins into
      # the container, the container will install them into the
      # virtual environment on startup
      - ./:/plugins:ro
